-- Generated RDBMS Schema
-- Dialect: PostgreSQL
-- Generated by RDBMS Builder


-- Organizations that own and manage vehicle fleets
CREATE TABLE companies (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    registration_number VARCHAR(100) NOT NULL UNIQUE,
    address TEXT NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Motorized transport units owned by companies
CREATE TABLE vehicles (
    id UUID PRIMARY KEY,
    license_plate VARCHAR(20) NOT NULL UNIQUE,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    year INTEGER NOT NULL,
    vehicle_type VARCHAR(50) NOT NULL,
    vin VARCHAR(17) NOT NULL UNIQUE,
    color VARCHAR(50) NOT NULL,
    mileage INTEGER NOT NULL DEFAULT 0,
    company_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicles_company_id FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- Persons authorized to operate company vehicles
CREATE TABLE drivers (
    id UUID PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    license_number VARCHAR(50) NOT NULL UNIQUE,
    license_expiry_date DATE NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    company_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_drivers_company_id FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- Company employees with administrative access to fleet data
CREATE TABLE managers (
    id UUID PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(100) NOT NULL,
    permissions JSONB NOT NULL,
    company_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_managers_company_id FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- Current assignments of drivers to specific vehicles
CREATE TABLE driver_assignments (
    id UUID PRIMARY KEY,
    driver_id UUID NOT NULL,
    vehicle_id UUID NOT NULL,
    assigned_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_driver_assignments_driver_id FOREIGN KEY (driver_id) REFERENCES drivers(id),
    CONSTRAINT fk_driver_assignments_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

-- Planned maintenance activities for vehicles
CREATE TABLE maintenance_schedules (
    id UUID PRIMARY KEY,
    vehicle_id UUID NOT NULL,
    maintenance_type VARCHAR(100) NOT NULL,
    scheduled_date DATE NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL DEFAULT scheduled,
    estimated_cost DECIMAL(10,2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_maintenance_schedules_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

-- Records of fuel consumption for vehicles
CREATE TABLE fuel_logs (
    id UUID PRIMARY KEY,
    vehicle_id UUID NOT NULL,
    driver_id UUID NOT NULL,
    fuel_date DATE NOT NULL,
    fuel_amount DECIMAL(8,2) NOT NULL,
    fuel_cost DECIMAL(10,2) NOT NULL,
    odometer INTEGER NOT NULL,
    location VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fuel_logs_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_fuel_logs_driver_id FOREIGN KEY (driver_id) REFERENCES drivers(id)
);

-- GPS tracking data for vehicle positions
CREATE TABLE vehicle_locations (
    id UUID PRIMARY KEY,
    vehicle_id UUID NOT NULL,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(11,8) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    speed DECIMAL(5,2),
    heading DECIMAL(5,2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicle_locations_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

-- Generated reports on fleet performance and analytics
CREATE TABLE fleet_reports (
    id UUID PRIMARY KEY,
    report_type VARCHAR(100) NOT NULL,
    company_id UUID NOT NULL,
    generated_by UUID NOT NULL,
    report_date DATE NOT NULL,
    parameters JSONB,
    file_path VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fleet_reports_company_id FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_fleet_reports_generated_by FOREIGN KEY (generated_by) REFERENCES managers(id)
);
